# SHAPE AND RESHAPING IN NUMPY ARRAYS 

In [2]:
import numpy as np

var = np.array([[3,4,6,4], [43,3,7,5]])
print(var)
print()
print(var.shape)

[[ 3  4  6  4]
 [43  3  7  5]]

(2, 4)


In [9]:
var1 = np.array([1,2,3,4], ndmin = 4)
print(var1)
print()
print(var1.shape)
print(var1.ndim)

[[[[1 2 3 4]]]]

(1, 1, 1, 4)
4


In [5]:
# Reshaping

var2 = np.array([1,2,3,4,5,6])
print("Original Array: ", var2)
print("Shape of Original Array: ", var2.shape)
print("Dimension of original Array: ", var2.ndim)

print()

x = var2.reshape(3, 2)
print("New Array: ", x)
print("Shape of new Array: ", x.shape)
print("Dimension of new Array: ", x.ndim)

Original Array:  [1 2 3 4 5 6]
Shape of Original Array:  (6,)
Dimension of original Array:  1

New Array:  [[1 2]
 [3 4]
 [5 6]]
Shape of new Array:  (3, 2)
Dimension of new Array:  2


In [8]:
var3 = np.array([1,2,3,4,5,6,5,6,3,3,6,8])
print("Original Array: ", var3)
print("Shape of Original Array: ", var3.shape)
print("Dimension of original Array: ", var3.ndim)

print()

x1 = var3.reshape(2, 3, 2)
print("New Array: ", x1)
print("Shape of new Array: ", x1.shape)
print("Dimension of new Array: ", x1.ndim) 

Original Array:  [1 2 3 4 5 6 5 6 3 3 6 8]
Shape of Original Array:  (12,)
Dimension of original Array:  1

New Array:  [[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [3 3]
  [6 8]]]
Shape of new Array:  (2, 3, 2)
Dimension of new Array:  3


In [12]:
# 3-D array into 1-D array
var3 = np.array([1,2,3,4,5,6,5,6,3,3,6,8])
print("Original Array: ", var3)
print("Shape of Original Array: ", var3.shape)
print("Dimension of original Array: ", var3.ndim)

print()

x1 = var3.reshape(2, 3, 2)
print("New Array: ", x1)
print("Shape of new Array: ", x1.shape)
print("Dimension of new Array: ", x1.ndim) 

print()

oneD = x1.reshape(-1)
print("One dimension array: ",oneD)
print("Dimension check: ",oneD.ndim)

Original Array:  [1 2 3 4 5 6 5 6 3 3 6 8]
Shape of Original Array:  (12,)
Dimension of original Array:  1

New Array:  [[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [3 3]
  [6 8]]]
Shape of new Array:  (2, 3, 2)
Dimension of new Array:  3

One dimension array:  [1 2 3 4 5 6 5 6 3 3 6 8]
Dimension check:  1
