# WHAT ARE NUMPY ARRAY FUNCTIONS?

# SEARCH ARRAY

In [4]:
import numpy as np 

var = np.array([1,2,3,4,6,8,4,2,5,78,86,4])
x = np.where( (var%2) == 0)
print("Position: ", x)

Position:  (array([ 1,  3,  4,  5,  6,  7,  9, 10, 11], dtype=int64),)


In [7]:
var1 = np.array([1,2,3,4,6,8,4,2,5,78,86,4])
x1 = np.where( var == 0)
print("Position: ", x1)

Position:  (array([], dtype=int64),)


# SEARCH SORTED ARRAY

In [13]:
var2 = np.array([1,2,3,4,6,7,8,9])

x2 = np.searchsorted(var2, 5, side = "right")
print("5 will be placed at position", x2, "in var2")

x3 = np.searchsorted(var2, [5,6,7], side = "right")
print(x3)

5 will be placed at position 4 in var2
[4 5 6]


# SORT ARRAY

In [2]:
var3 = np.array([4,5,6,7,8,46,56,27,3])
print(np.sort(var3))

[ 3  4  5  6  7  8 27 46 56]


In [3]:
var4 = np.array(['f', 'g', 'u', 's', 'b', 'r', 'q', 'i', 'p', 'a', 'x'])
print(np.sort(var4))

['a' 'b' 'f' 'g' 'i' 'p' 'q' 'r' 's' 'u' 'x']


In [5]:
var5 = np.array([[4,5,6], [6,5,3], [7,8,5]])
print(np.sort(var5))

[[4 5 6]
 [3 5 6]
 [5 7 8]]


# FILTER ARRAY

In [9]:
var6 = np.array(['f', 'g', 'u', 's', 'b', 'r', 'q'])
print("Array before filter: ", var6)

filter_array = [True, False, False, True, False, True, True]
new_array = var6[filter_array]

print("Array after filter: ", new_array)
print(type(new_array))

Array before filter:  ['f' 'g' 'u' 's' 'b' 'r' 'q']
Array after filter:  ['f' 's' 'r' 'q']
<class 'numpy.ndarray'>


# ARITHMETIC FUNCTIONS 

# 1. SHUFFLE FUNCTION 

In [10]:
var7 = np.array([2,3,45,6,7,7])
np.random.shuffle(var7)
print(var7)

[45  3  7  6  2  7]


# 2. UNIQUE FUNCTION

In [19]:
var8 = np.array([5,5,3,3,5,7,8,0,5,3,5,7,8,3,4,7,9])
print("Original Data: ", var8)

x = np.unique(var8)
print("Unique Data: ", x)

Original Data:  [5 5 3 3 5 7 8 0 5 3 5 7 8 3 4 7 9]
Unique Data:  [0 3 4 5 7 8 9]


In [18]:
var9 = np.array([5,5,3,3,5,7,8,0,5,3,5,7,8,3,4,7,9])
print("Original Data: ", var9)

x = np.unique(var9, return_index = True, return_counts = True)
print("Unique Data: ", x)

Original Data:  [5 5 3 3 5 7 8 0 5 3 5 7 8 3 4 7 9]
Unique Data:  (array([0, 3, 4, 5, 7, 8, 9]), array([ 7,  2, 14,  0,  5,  6, 16], dtype=int64), array([1, 4, 1, 5, 3, 2, 1], dtype=int64))


# 3. RESIZE FUNCTION

In [20]:
var10 = np.array([2,3,4,5,7,8])
y = np.resize(var10, (2,3))
print(y)

[[2 3 4]
 [5 7 8]]


# 4. FLATTEN AND RAVEL FUNCTION 

In [29]:
var11 = np.array([2,3,4,5,7,8])

y = np.resize(var11, (2,3))
print("Original Array: \n", y)
print()

print("Array after using flatten function: ", y.flatten())

Original Array: 
 [[2 3 4]
 [5 7 8]]

Array after using flatten function:  [2 3 4 5 7 8]


In [27]:
var11 = np.array([2,3,4,5,7,8])

y = np.resize(var11, (2,3))
print("Original Array: \n", y)

print()

print("Array after using flatten function:", y.flatten(order = "F"))

Original Array: 
 [[2 3 4]
 [5 7 8]]

Array after using flatten function: [2 5 3 7 4 8]


In [6]:
var11 = np.array([2,3,4,5,7,8])

y = np.resize(var11, (2,3))
print("Original Array: \n", y)

print()

print("Array after using flatten function:", y.flatten(order = "F"))
print("Array after using ravel function: ", np.ravel(y, order = "F"))
print()

print("Array after using flatten function:", y.flatten(order = "C"))
print("Array after using ravel function: ", np.ravel(y, order = "C"))
print()

print("Array after using flatten function:", y.flatten(order = "A"))
print("Array after using ravel function: ", np.ravel(y, order = "A"))
print()

print("Array after using flatten function:", y.flatten(order = "K"))
print("Array after using ravel function: ", np.ravel(y, order = "K"))

Original Array: 
 [[2 3 4]
 [5 7 8]]

Array after using flatten function: [2 5 3 7 4 8]
Array after using ravel function:  [2 5 3 7 4 8]

Array after using flatten function: [2 3 4 5 7 8]
Array after using ravel function:  [2 3 4 5 7 8]

Array after using flatten function: [2 3 4 5 7 8]
Array after using ravel function:  [2 3 4 5 7 8]

Array after using flatten function: [2 3 4 5 7 8]
Array after using ravel function:  [2 3 4 5 7 8]
