# NUMPY INSERT AND DELETE ARRAYS FUNCTIONS

# INSERT

In [7]:
import numpy as np 

var = np.array([1,2,3,4])
print("Original Array: ", var)

var1 = np.insert(var, 2, 40)
print("New Array: ", var1)

var2 = np.insert(var, (2,4), 40)
print("New Array: ", var2)

Original Array:  [1 2 3 4]
New Array:  [ 1  2 40  3  4]
New Array:  [ 1  2 40  3  4 40]


In [19]:
var3 = np.array([[3,4,55,4], [5,7,8,5]])
print("Original array: \n", var3)
print()

var4 = np.insert(var3, 2, 6, axis=1)
print("New array: \n", var4)

var5 = np.insert(var3, 2, [22,23], axis=1)
print("New array: \n", var4)

Original array: 
 [[ 3  4 55  4]
 [ 5  7  8  5]]

New array: 
 [[ 3  4  6 55  4]
 [ 5  7  6  8  5]]
New array: 
 [[ 3  4 22 55  4]
 [ 5  7 23  8  5]]


In [22]:
# using insert function with append 

var6 = np.array([1,2,3,4])
print("Original Array: ", var6)

x = np.append(var6, 6.5)
print("New Array: ", x)

Original Array:  [1 2 3 4]
New Array:  [1.  2.  3.  4.  6.5]


In [27]:
var7 = np.array([[3,4,55,4], [5,7,8,5]])
print("Original array: \n", var7)
print()

var8 = np.append(var7, [[45,44,23,87]], axis=0)
print("New Array: \n", var8)
print()

Original array: 
 [[ 3  4 55  4]
 [ 5  7  8  5]]

New Array: 
 [[ 3  4 55  4]
 [ 5  7  8  5]
 [45 44 23 87]]



# DELETE

In [31]:
import numpy as np 

var9 = np.array([1,2,3,4])
print("Original Array: \n", var9)
print()

d = np.delete(var9, 2)
print("New Array: ", d)

Original Array: 
 [1 2 3 4]
New Array:  [1 2 4]
