# CONCEPT OF MATRIX NUMPY ARRAYS IN PYTHON

In [1]:
import numpy as np 
var = np.matrix([[1,2], [1,2]])
var2 = np.matrix([[5,7], [7,5]])

print(var)
print(type(var))
print()
print(var + var2)
print(var - var2)
print(var * var2)
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[6 9]
 [8 7]]
[[-4 -5]
 [-6 -3]]
[[19 17]
 [19 17]]
[[19 17]
 [19 17]]


In [3]:
var1 = np.array([[1,2,3], [1,2,3]])
print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]
