# MATRIX FUNCTION IN NUMPY ARRAY

In [2]:
# TRANSPOSE
import numpy as np 
var = np.matrix([[1,2,3], [4,5,6]])
print(var)
print()
    
print(np.transpose(var))
print()
# OR
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [7]:
# SWAPAXES
print(np.swapaxes(var, 0, 1))

[[1 4]
 [2 5]
 [3 6]]


In [9]:
var2 = np.matrix([[1,2], [3,4]])
print(var2)
print()
print(np.swapaxes(var2, 0, 1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [10]:
# INVERSE
var3 = np.matrix([[1,2], [3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
# POWER
var4 = np.matrix([[1,2], [3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4, 2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]



In [4]:
# DETERMINATE
var5 = np.matrix([[1,2], [3,4]])
print(var5)
print()

print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004
