# CREATING ARRAYS

In [7]:
import numpy as np 

x = [1,2,3,4]
y = np.array(x)

print(y) 
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y) 

[1 2 3 4 5]


In [3]:
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
y 

array([1, 2, 3, 4, 5])

In [5]:
l = []

for i in range(1,5):
    int_1 = int(input("Enter a value: "))
    l.append(int_1) 
    
print(np.array(l))

Enter a value: 2
Enter a value: 3
Enter a value: 4
Enter a value: 5
[2 3 4 5]


In [8]:
ar2 = np.array([[1,2,3,4], [1,2,3,5]]) 
print(ar2) 
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 5]]
2


In [9]:
ar3 = np.array([[[1,2,3,4], [2,3,4,5], [3,4,5,6], [4,5,6,7]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]]
3


# SPECIAL NUMPYA ARRAYS 

In [19]:
# ARRAY FILLED WITH 0'S
import numpy as np

arr_zero_array = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero_array)
print("Single dimension array: \n", arr_zero1)

[0. 0. 0. 0.]
Single dimension array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [18]:
# ARRAY FILLED WITH 1'S
arr_one_array = np.ones(4)
arr_one1 = np.ones((3,4,))

print(arr_one_array)
print("One dimensional array: \n", arr_one1)

[1. 1. 1. 1.]
One dimensional array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# CREATE AN EMPTY ARRAY
arr_empty_array = np.empty(4)
print(arr_empty_array)

[1. 1. 1. 1.]


In [20]:
# AN ARRAY WITH A RANGE OF ELEMENT
arr_range_array = np.arange(4)
print(arr_range_array)

[0 1 2 3]


In [24]:
# ARRAY DIAGONAL ELEMENT FILLED WITH 1'S
arr_diagonal_array = np.eye(3)
print(arr_diagonal_array)

print() 

arr_diagonal_array = np.eye(3,5)
print(arr_diagonal_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [30]:
# CREATE AN ARRAY WITH VALUES THAT ARE SPACED LINEARLY IN A SPECIFIED INTERVAL
arr_lin_array = np.linspace(1,50,num=5)
print(arr_lin_array)

[ 1.   13.25 25.5  37.75 50.  ]


# CREATE NUMPY ARRAY WITH RANDOM NUMBERS

In [32]:
# rand()
import numpy as np
var = np.random.rand(4)
print(var)

var1 = np.random.rand(2,5)
print(var1)

[0.93319998 0.60323189 0.90248598 0.57330845]


In [35]:
# randn() 
var2 = np.random.randn(10)
print(var2) 

[ 0.10300801 -1.02732481  0.21707284 -1.50968866 -0.15350364 -0.02713856
 -0.22225344 -2.82895842 -2.20038278  1.95449287]


In [36]:
# ranf()
var3 = np.random.ranf(5)
print(var3)

[0.17452505 0.43805408 0.86422119 0.69416283 0.52616741]


In [37]:
# randint()
var4 = np.random.randint(5,20,5)
print(var4)

[ 6 18 10 17  8]
