DATA TYPES OF NUMPY ARRAYS 

In [1]:
import numpy as np 

var = np.array([1,2,3,4])
print("Data type: ", var.dtype)

Data type:  int32


In [2]:
var = np.array([1.0,2.7,3.6,4.4])
print("Data type: ", var.dtype)

Data type:  float64


In [3]:
var = np.array(['a','f','d','s'])
print("Data type: ", var.dtype)

Data type:  <U1


In [4]:
var = np.array([1,2,3,4, 'j', 'g', 's'])
print("Data type: ", var.dtype)

Data type:  <U11


In [7]:
# change data type
X = np.array([1,2,3,4], dtype = np.int8)

print("Data type: ", X.dtype)
print(X) 

Data type:  int8
[1 2 3 4]


In [8]:
X1 = np.array([1,2,3,4], dtype = "f")

print("Data type: ", X1.dtype)
print(X1) 

Data type:  float32
[1. 2. 3. 4.]


In [10]:
X2 = np.array([1,2,3,4])

new = np.float32(X2) 

print("Data type: ", X2.dtype)
print("Data type: ", new.dtype)

print(X2) 
print(new) 

Data type:  int32
Data type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [11]:
X2 = np.array([1,2,3,4])

new = np.float32(X2)
new1 = np.int_(new)

print("Data type: ", X2.dtype)
print("Data type: ", new.dtype)
print("Data type: ", new1.dtype)

print(X2) 
print(new) 
print(new1) 

Data type:  int32
Data type:  float32
Data type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [5]:
import numpy as np
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
