# NUMPY ARITHMETIC OPERATIONS

In [ ]:
# one-dimension array

In [1]:
import numpy as np

var = np.array([1,2,3,4])
var_add = var + 3

print(var_add)

[4 5 6 7]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,4,6])

var_add = var1 + var2
print(var_add)

[ 2  4  7 10]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,4,6])

var_add = np.add(var1, var2)
print(var_add)

[ 2  4  7 10]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,4,6])

var_add = np.add(var1, 3)
print(var_add)

[4 5 6 7]


In [5]:
# two dimension array

In [11]:
var3 = np.array([[1,2,3,4], [1,3,5,6]])
var4 = np.array([[1,2,3,4], [1,3,5,6]])

print(var3)
print("+")
print(var4)
print("=")

var_add = np.add(var3, var4)
print(var_add)

[[1 2 3 4]
 [1 3 5 6]]
+
[[1 2 3 4]
 [1 3 5 6]]
=
[[ 2  4  6  8]
 [ 2  6 10 12]]


In [12]:
var3 = np.array([[1,2,3,4], [1,3,5,6]])
var4 = np.array([[1,2,3,4], [1,3,5,6]])

print(var3)
print("*")
print(var4)
print("=")

var_mul = np.multiply(var3, var4)
print(var_mul)

[[1 2 3 4]
 [1 3 5 6]]
*
[[1 2 3 4]
 [1 3 5 6]]
=
[[ 1  4  9 16]
 [ 1  9 25 36]]


In [1]:
# Reciprocal

In [4]:
import numpy as np
var = np.array([1,2,3,4])
var_reciprocal = np.reciprocal(var)

print(var_reciprocal)

[1 0 0 0]
