# ITERATING NUMPY ARRAY

In [1]:
import numpy as np

var = np.array([9,4,5,7,3,2,6,7,6,5])

print("Array is: ", var)
print()
print("Array after Iteration: ")

for i in var:
    print(i)

Array is:  [9 4 5 7 3 2 6 7 6 5]

Array after Iteration: 
9
4
5
7
3
2
6
7
6
5


In [9]:
var1 = np.array([[1,53,3], [5,87,3]])
print("Array is: ", var1)
print()
print("Array after iteration is: ")

# for j in var1:
#     print(j)
    
# print()
# print("Array after iteration: ")

for k in var1:
    for l in k:
        print(l)

Array is:  [[ 1 53  3]
 [ 5 87  3]]

Array after iteration is: 
1
53
3
5
87
3


In [12]:
var2 = np.array([[[2,3,5], [5,6,4], [4,5,4]]])
print("Array is", var2)
print("Dimension of Array is: ", var2.ndim)
print()
print("After Iteration Array is: ")

for i in var2:
    for j in i:
        for k in j:
            print(k)

Array is [[[2 3 5]
  [5 6 4]
  [4 5 4]]]
Dimension of Array is:  3

After Iteration Array is: 
2
3
5
5
6
4
4
5
4


In [5]:
var2 = np.array([[[2,3,5], [5,6,4], [4,5,4]]])
print("Array is", var2)
print("Dimension of Array is: ", var2.ndim)
print()
print("After Iteration Array is: ")

for i in np.nditer(var2, flags=['buffered'], op_dtypes = ["S"]):
    print(i)

Array is [[[2 3 5]
  [5 6 4]
  [4 5 4]]]
Dimension of Array is:  3

After Iteration Array is: 
b'2'
b'3'
b'5'
b'5'
b'6'
b'4'
b'4'
b'5'
b'4'


In [2]:
var3 = np.array([[[2,3,5], [5,6,4], [4,5,4]]])
print("Array is", var3)
print("Dimension of Array is: ", var3.ndim)
print()
print("After Iteration Array is: ")

for i,d in np.ndenumerate(var3):
    print(i, d)

Array is [[[2 3 5]
  [5 6 4]
  [4 5 4]]]
Dimension of Array is:  3

After Iteration Array is: 
(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 5
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 4
(0, 2, 0) 4
(0, 2, 1) 5
(0, 2, 2) 4
