# JOINING AND SPLIT NUMPY ARRAYS

# JOIN ARRAY

In [2]:
import numpy as np 

var = np.array([1,2,3,4])
print("1st Array is: ", var)

var1 = np.array([9,8,7,6]) 
print("2nd Array is: ", var1)

arr = np.concatenate((var, var1))

print("After using concatenate function, new array is: ", arr)

1st Array is:  [1 2 3 4]
2nd Array is:  [9 8 7 6]
After using concatenate function, new array is:  [1 2 3 4 9 8 7 6]


In [5]:
var2 = np.array([[1,2],[3,4]])
print("1st Array is: \n", var2)

var3 = np.array([[9,8],[7,6]]) 
print("2nd Array is: \n", var3)

arr2 = np.concatenate((var2, var3), axis = 1)

print("After using concatenate function, new array is: \n", arr)

1st Array is: 
 [[1 2]
 [3 4]]
2nd Array is: 
 [[9 8]
 [7 6]]
After using concatenate function, new array is: 
 [[1 2 9 8]
 [3 4 7 6]]


In [ ]:
var4 = np.array([1,2,3,4])
print("1st Array is: ", var4)

var5 = np.array([9,8,7,6]) 
print("2nd Array is: ", var5)

arr3 = np.concatenate((var4, var5))

print("After using concatenate function, new array is: ", arr)

In [6]:
var6 = np.array([1,2,3,4])
var7 = np.array([9,7,8,6])

arr_new = np.stack((var6, var7), axis = 1)
arr_new1 = np.dstack((var6, var7))   #along height
arr_new2 = np.vstack((var6, var7))   #along column
arr_new3 = np.hstack((var6, var7))   #along row 

print(arr_new) 
print()
print(arr_new1) 
print()
print(arr_new2) 
print()
print(arr_new3) 

[[1 9]
 [2 7]
 [3 8]
 [4 6]]

[[[1 9]
  [2 7]
  [3 8]
  [4 6]]]

[[1 2 3 4]
 [9 7 8 6]]

[1 2 3 4 9 7 8 6]


# SPLIT ARRAY 

In [15]:
var8 = np.array([1,2,3,4,5,6])
print(var8)
print()

arr4 = np.array_split(var,3)
print(arr4)
print(type(arr4))
print(arr[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3]), array([4])]
<class 'list'>
[1 2]


In [20]:
var9 = np.array([[1,2,3], [4,5,8], [98,5,3]])
print("Original array: ", var9)
print()

arr5 = np.array_split(var9, 3)
arr6 = np.array_split(var9, 3, axis = 1)

print()
print("After splitting: \n", arr5)
print()
print("After splitting through axis: \n", arr6)

Original array:  [[ 1  2  3]
 [ 4  5  8]
 [98  5  3]]


After splitting: 
 [array([[1, 2, 3]]), array([[4, 5, 8]]), array([[98,  5,  3]])]

After splitting through axis: 
 [array([[ 1],
       [ 4],
       [98]]), array([[2],
       [5],
       [5]]), array([[3],
       [8],
       [3]])]
